MODEL:
  TYPE: resnet
  DEPTH: 50
  NUM_CLASSES: 100
RESNET:
  TRANS_FUN: bottleneck_transform
  NUM_GROUPS: 1
  WIDTH_PER_GROUP: 64
  STRIDE_1X1: False
BN:
  ZERO_INIT_FINAL_GAMMA: False
OPTIM:
  BASE_LR: 0.1
  LR_POLICY: steps
  STEPS: [0]
  MAX_EPOCH: 10
  MOMENTUM: 0.9
  NESTEROV: False
  WEIGHT_DECAY: 5e-5
TRAIN:
  AUTO_RESUME: True
  DATASET: imagenet
  SPLIT: train
  BATCH_SIZE: 256
  IM_SIZE: 224
  WEIGHTS: ./resnet50_100.pt
ADV:
  TRAIN_ATTACK: patchpgd
  TRAIN_NUM_STEPS: 10
  TRAIN_STEP_SIZE: 0.25
  TRAIN_PATCH_SIZES: [10, 50]
  VAL_ATTACK: patchpgd
  VAL_NUM_STEPS: 40
  VAL_STEP_SIZE: 0.02
  VAL_PATCH_SIZE: 50
  VAL_NUM_RESTARTS: 1
TEST:
  DATASET: imagenet
  SPLIT: val
  BATCH_SIZE: 512
  IM_SIZE: 224
NUM_GPUS: 8
DATA_LOADER:
  NUM_WORKERS: 10
CUDNN:
  BENCHMARK: True
LOG_PERIOD: 100
LOG_DEST: stdout
OUT_DIR: ./outputs/patchadv/train_resnet_adv
WANDB:
  ENABLED: False